@java_double
Feature: Java feature

  @java_double1
  Scenario: Hello World
#      Given I hello world (double)
#      Given I compare "my var" and "my VAR" (double)
#      Given I compare "cloud" and "cloud" strings (double)
#      Given I compare "cloud" and "Cloud" strings (double)
#      Given I compare "cloud" and "sun" strings (double)
#      Given I print url for "google.com" page (double)
#      Given I print url for "yandex.ru" page (double)
#      Given compare numbers 10 and 3 (double)
#      Given compare numbers 100 and 300 (double)
#      Given compare numbers 3 and 3 (double)
#      And I print url for "yahoo" page (double)
#    And I repeat the word "Mysh" 5 times with the help of loops (double)
#      And I print if number 35 is positive (double)
#      And I print if number -17 is positive (double)
#      And I print if number 0 is positive (double)
#      And I print 7 day of week (double)
#      And I print 2 day of week (double)
#      And I work with arrays (double)

#      And I print all numbers from 0 up to 12 (double)
#      And I print all numbers from -12 up to 0 (double)
#      And I print all integer array (double)
#      And I print all even numbers from integer array (double)
#      And I check if array is empty (double)
#      And I check if array contains 12 (double)
#      And I check if array contains 10 (double)
#      And I check if array contains "no" (double)
#      And I check if array contains "n" (double)


#      And I sort an array (double)
#      Given I swap two variables (double)
#      And I convert a string "200" into int (double)
#      And I check the division of 15 (double)
#      And I check the division of 11 (double)
#      And I check the division of 6 (double)
#      And I am playing a FizzBuzz game (double)
#      And I am playing a Fibonacci game (double)
#      And I am looking for the largest element in an array (double)
#      And I reverse a string "Hello" (double)
#      And I reverse words in a sentence "The Sun is shining" (double)

#      And I check if there are duplicates in an array (double)
#      And I determine if "civic" is a palindrome (double)
#      And I determine if "anna" is a palindrome (double)
#      And I determine if "qwerty" is a palindrome (double)
#      And I find the max number in array (double)
#      And I find two max numbers in array (double)
#      And I find the min number in array (double)
#      ???And I find if any two elements of an array result in sum  (double)

#      And I find if 11 is a prime number (double)
#      And I find if 12 is a prime number (double)
#      And I find if 0 is a prime number (double)
#      And I find if 1 is a prime number (double)
#      And I find factorial of 5 (double)
#      And I find factorial of 1 (double)
#      And I find factorial of 0 (double)
#      And I check whether "Z" is a vowel or not (double)
#      And I check whether "a" is a vowel or not (double)
